BACE:
- Class
BBBP:
- p_np
ClinTox:
- CT_TOX
- FDA_APPROVED
ESOL:
- measured log solubility in mols per litre
FreeSolv:
- expt
HIV:
- HIV_active
Lipo:
- exp
MUV:
- MUV-692
- MUV-689
- MUV-846
- MUV-859
- MUV-644
- MUV-548
- MUV-852
- MUV-600
- MUV-810
- MUV-712
- MUV-737
- MUV-858
- MUV-713
- MUV-733
- MUV-652
- MUV-466
- MUV-832
SIDER:
- Hepatobiliary disorders
- Metabolism and nutrition disorders
- Product issues
- Eye disorders
- Investigations
- Musculoskeletal and connective tissue disorders
- Gastrointestinal disorders
- Social circumstances
- Immune system disorders
- Reproductive system and breast disorders
- Neoplasms benign, malignant and unspecified (incl cysts and polyps)
- General disorders and administration site conditions
- Endocrine disorders
- Surgical and medical procedures
- Vascular disorders
- Blood and lymphatic system disorders
- Skin and subcutaneous tissue disorders
- Congenital, familial and genetic disorders
- Infections and infestations
- Respiratory, thoracic and mediastinal disorders
- Psychiatric disorders
- Renal and urinary disorders
- Pregnancy, puerperium and perinatal conditions
- Ear and labyrinth disorders
- Cardiac disorders
- Nervous system disorders
- Injury, poisoning and procedural complications
Tox21:
- NR-AR
- NR-AR-LBD
- NR-AhR
- NR-Aromatase
- NR-ER
- NR-ER-LBD
- NR-PPAR-gamma
- SR-ARE
- SR-ATAD5
- SR-HSE
- SR-MMP
- SR-p53
qm7:
- u0_atom
qm8:
- E1-CC2
- E2-CC2
- f1-CC2
- f2-CC2
- E1-PBE0
- E2-PBE0
- f1-PBE0
- f2-PBE0
- E1-CAM
- E2-CAM
- f1-CAM
- f2-CAM
qm9:
- mu
- alpha
- homo
- lumo
- gap
- r2
- zpve
- cv
